name: Daily Refresh — AI Dashboard

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * *"   # 08:00 America/Chicago during CDT (UTC-5)
    - cron: "0 14 * * *"   # 08:00 America/Chicago during CST (UTC-6)

permissions:
  contents: write

concurrency:
  group: ai-dashboard-refresh
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      OUTPUT_JSON: data/ai_dashboard.json
      NEWS_API_PROVIDER: "rss"   # change to 'newsapi' and add NEWS_API_KEY secret if desired
      NEWS_WINDOW_DAYS: "2"
      NEWS_QUERY: "AI OR artificial intelligence OR generative AI"
      TOP_N_SOURCES: "40"
      TOP_N_ITEMS: "5"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update Top-5 news
        run: python scripts/update_news.py

      - name: Recompute leaderboard
        run: python scripts/update_leaderboard.py

      - name: Commit dashboard JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 8am CT dashboard refresh (news + leaderboard)"
          file_pattern: data/ai_dashboard.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

