name: Refresh AI Dashboard

on:
  schedule:
    - cron: '0 13 * * *'  # 08:00 America/Chicago
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil
      - name: Update news
        run: python scripts/get_ai_news.py
      - name: Recompute leaderboard
        run: python scripts/update_leaderboard.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: 8am CT dashboard refresh (news + leaderboard)"
          add: "data/ai_dashboard.json"
